services:
  main-site:
    image: ghcr.io/zhuyidian/yidian-host:main
    pull_policy: always
    container_name: yidianhub-main
    restart: unless-stopped
    networks:
      caddy_frontend:
        aliases:
          - yidianhub-main

networks:
  caddy_frontend:
    external: true
    name: yidian-api_frontend
